#!/bin/bash
# This is a wrapper for the /bin/mail program that will try to get the current
# on call person's email address from NaGCal.
#
# If successful, it will tell /bin/mail to send to that address.
#
# If NaGCal exits with a non-zero exit code however, /bin/mail will be told
# to send to the fallback address provided as an argument to this script.
#
NAGCAL_PATH=nagcal
MAIL_PATH=mail
CACHE_PATH=/tmp

NO_ARGS=0
E_OPTERROR=85
USAGE_MSG="Usage: `basename $0` -f /path/to/nagcal.cfg -w /tmp -s \"Subject\" fallback.email@example.com"

if [ $# -eq "$NO_ARGS" ]    # Script invoked with no command-line args?
then
    echo $USAGE_MSG; exit $E_OPTERROR
fi

while getopts "s:f:w:" Option
do
    case $Option in
        s     ) SUBJECT=$OPTARG;;
        f     ) NAGCAL_CONFIG=$OPTARG;;
        w     ) CACHE_PATH=$OPTARG;;
        *     ) echo "Unimplemented option."; echo $USAGE_MSG; exit $E_OPTERROR;;
    esac
done

NAGCAL="$NAGCAL_PATH --config=$NAGCAL_CONFIG"

shift $(($OPTIND - 1))

if [ $# -eq "$NO_ARGS" ] # No argument left after options?
then
    echo "You must specify a fallback e-mail address!"
    echo $USAGE_MSG; exit $E_OPTERROR
fi

if [[ ( ! -d "$CACHE_PATH" ) || ( ! -w "$CACHE_PATH" ) ]]
then
	echo "Can't write to provided cache directory!"
	echo $USAGE_MSG; exit $E_OPTERROR
fi

cd $CACHE_PATH # need to be in a directory writable by current user

FALLBACK=$1
ONCALL=$($NAGCAL --current --email)
ONCALL_EXIT=$?

if [ $ONCALL_EXIT == 0 ]
then
    EMAIL=$ONCALL
else
    EMAIL=$FALLBACK
fi

$MAIL_PATH -s "$SUBJECT" $EMAIL
exit $?
